### ISSUE TITLE
definition does not exist in the config from git-info module

### ISSUE THREAD

**Issue by hobochild** [balena-io/landr#63]
```
[petrosagg@satie balena]$ landr 
Error: Branch ("17.06-resin") definition does not exist in the config.
    at Object.gitinfo.getRemoteUrl (/home/petrosagg/node_modules/gitinfo/dist/gitinfo.js:816:13)
    at Object.gitinfo.getUsername (/home/petrosagg/node_modules/gitinfo/dist/gitinfo.js:868:59)
    at _callee$ (/home/petrosagg/node_modules/landr/dist/data/plugins/github.js:37:30)
    at tryCatch (/home/petrosagg/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/petrosagg/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/petrosagg/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/petrosagg/node_modules/landr/dist/data/plugins/github.js:3:191)
    at /home/petrosagg/node_modules/landr/dist/data/plugins/github.js:3:437
    at Promise._execute (/home/petrosagg/node_modules/landr/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/petrosagg/node_modules/landr/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/petrosagg/node_modules/landr/node_modules/bluebird/js/release/promise.js:79:10)
    at /home/petrosagg/node_modules/landr/dist/data/plugins/github.js:3:99
    at /home/petrosagg/node_modules/landr/dist/data/plugins/github.js:104:18
    at /home/petrosagg/node_modules/landr/dist/data/index.js:21:12
    at tryCatcher (/home/petrosagg/node_modules/landr/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/petrosagg/node_modules/landr/node_modules/bluebird/js/release/map.js:61:38)
```

**Comment by craig-mulligan** [comment]
Initially suspected it was due to multiple remotes, but tested it on my setup and handled that fine. Need to dig into the `git-info` module again.
